apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helm-guestbook
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9898
  selector:
    app: {{ .Release.Name }}-helm-guestbook
